server:
  port: 9003
spring:
  application:
    name: yc-provider-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:9001/eureka/
  instance:
    prefer-ip-address: true