server:
  port: 9001
spring:
  application:
    name: yc-eureka
  security:
    user:
      name: root
      password: 123456
eureka:
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/